### ISSUE TITLE
Config failure 

### ISSUE THREAD

**Issue by williamkibira** [pineda89/golang-springboot#1]
Hello 
I am having an issue with the example application failing to start
It loads the config correctly but still fails to start
here is the error
`
 2017/12/14 10:56:58 Config loaded correctly
panic: interface conversion: interface {} is nil, not string

goroutine 11 [running]:
github.com/pineda89/golang-springboot/eureka.Register(0xc4201100f0)
        /Users/willitanium/go/src/github.com/pineda89/golang-springboot/eureka/eureka.go:36 +0xf55
created by main.main
        /Users/willitanium/go/src/gitlab.com/nssc/nssc-auth/main.go:23 +0xcb
exit status 2
`

What could i be doing wrong perhaps ?

**Comment by pineda89** [comment]
Can you debug the connectivity between this lib and eureka?

**Comment by williamkibira** [comment]
Ow sorry , just seen this . Are you still getting knocked off when you try
to connect to eureka ?

**Comment by pineda89** [comment]
Now I don't work with eureka. The integration is deprecated sorry :(

**Comment by williamkibira** [comment]
I got it to work after cloning the code and changing a few things a while
back .

**Comment by pineda89** [comment]
no replies for + 1 year
